/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tk_rabidbeaver_radio_RadioWrapper */

#ifndef _Included_tk_rabidbeaver_radio_RadioWrapper
#define _Included_tk_rabidbeaver_radio_RadioWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     tk_rabidbeaver_radio_RadioWrapper
 * Method:    initRadio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tk_rabidbeaver_radio_RadioWrapper_initRadio
  (JNIEnv *, jobject);

/*
 * Class:     tk_rabidbeaver_radio_RadioWrapper
 * Method:    deinitRadio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tk_rabidbeaver_radio_RadioWrapper_deinitRadio
  (JNIEnv *, jclass);

/*
 * Class:     tk_rabidbeaver_radio_RadioWrapper
 * Method:    sendCommand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tk_rabidbeaver_radio_RadioWrapper_sendCommand
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
